import AudiA4 from "../../Assets/AudiA4.png";
import Porshe from "../../Assets/Porshe.png";
import Merc from "../../Assets/Merc.png";
import Golf8 from "../../Assets/Golf8.png";

export const CarData = [
  {
    id: 1,
    name: "Porshe 718 Cayman S",
    brand: "Porshe",
    type: "SUV",
    fav: true,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: Porshe,
    usage: "Used",
  },
  {
    id: 2,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "New",
  },
  {
    id: 3,
    name: "Volks Golf 8",
    brand: "Volks",
    type: "HatchBack",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Golf8,
    usage: "Used",
  },
  {
    id: 4,
    name: "Audi A4",
    brand: "Audi",
    type: "Sedan",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: AudiA4,
    usage: "New",
  },
  {
    id: 5,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "New",
  },
  {
    id: 6,
    name: "Porshe 718 Cayman S",
    brand: "Porshe",
    type: "SUV",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: Porshe,
    usage: "Used",
  },
  {
    id: 7,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "Used",
  },
  {
    id: 8,
    name: "Porshe 718 Cayman S",
    brand: "Porshe",
    type: "SUV",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: Porshe,
    usage: "New",
  },
  {
    id: 9,
    name: "Audi A4",
    brand: "Audi",
    type: "Sedan",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: AudiA4,
    usage: "Used",
  },
  {
    id: 10,
    name: "Volks Golf 8",
    brand: "Volks",
    type: "HatchBack",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Golf8,
    usage: "New",
  },
  {
    id: 11,
    name: "Porshe 718 Cayman S",
    brand: "Porshe",
    type: "SUV",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: Porshe,
    usage: "New",
  },
  {
    id: 12,
    name: "Audi A4",
    brand: "Audi",
    type: "Sedan",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: AudiA4,
    usage: "New",
  },
  {
    id: 13,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "Used",
  },
  {
    id: 14,
    name: "Audi A4",
    brand: "Audi",
    type: "Sedan",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: AudiA4,
    usage: "New",
  },
  {
    id: 15,
    name: "Volks Golf 8",
    brand: "Volks",
    type: "HatchBack",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Golf8,
    usage: "Used",
  },
  {
    id: 16,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "New",
  },
  {
    id: 17,
    name: "Porshe 718 Cayman S",
    brand: "Porshe",
    type: "SUV",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: Porshe,
    usage: "Used",
  },
  {
    id: 18,
    name: "Audi A4",
    brand: "Audi",
    type: "Sedan",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "400",
    carImg: AudiA4,
    usage: "Used",
  },
  {
    id: 19,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "Used",
  },
  {
    id: 20,
    name: "Volks Golf 8",
    brand: "Volks",
    type: "HatchBack",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Golf8,
    usage: "Used",
  },
  {
    id: 21,
    name: "Volks Golf 8",
    brand: "Volks",
    type: "HatchBack",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Golf8,
    usage: "Used",
  },
  {
    id: 22,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "New",
  },
  {
    id: 23,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "New",
  },
  {
    id: 24,
    name: "Mercedes CLA",
    brand: "Mercedes",
    type: "Coupe",
    fav: false,
    peopleNum: 0,
    trans: "Manual",
    price: "690",
    carImg: Merc,
    usage: "Used",
  },
];

export const carBrands = ["Any", "Audi", "Mercedes", "Volks", "Porshe"];
